#!/bin/env bash

# Options for powermenu
lock="Lock"
logout="Logout"
shutdown="Shutdown"
reboot="Reboot"
sleep="Suspend"

# Get answer from user via rofi
selected_option=$(echo "$sleep
$lock
$logout
$reboot
$shutdown" | rofi -dmenu\
                  -i\
                  -p "Power")

# Do something based on selected option
if [ "$selected_option" == "$lock" ]
then
    swaylock
elif [ "$selected_option" == "$logout" ]
then
    loginctl terminate-user `whoami`
elif [ "$selected_option" == "$shutdown" ]
then
    loginctl poweroff
elif [ "$selected_option" == "$reboot" ]
then
    loginctl reboot
elif [ "$selected_option" == "$sleep" ]
then
    loginctl suspend
else
    echo "No match"
fi
