[general]
live_config_reload = true
import = [
	"~/.config/alacritty/modus_vivendi.toml"
]

[window]
dynamic_title = true
option_as_alt = "OnlyLeft"

[font]
size = 14.0
normal = { family = "Iosevka NF", style = "Regular" }
