[general]
live_config_reload = true
import = [
	"~/.config/alacritty/vague.toml"
]

[window]
dynamic_title = true
option_as_alt = "OnlyLeft"

[font]
size = 13.0
normal = { family = "FiraCode Nerd Font Mono", style = "Regular" }
